# Generated by Django 4.2.4 on 2023-09-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0003_counter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Counter',
        ),
        migrations.AddField(
            model_name='shortenedurl',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
